name: Jekyll Test

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
    - name: Download Paseo chainspecs
      run: |
        wget --directory-prefix=downloads/paseo-chain-specs --input-file=paseo/urls.txt

    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site